CREATE TABLE IF NOT EXISTS species (
id BIGSERIAL PRIMARY KEY,
es_AR VARCHAR(255),
en_US VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS breeds (
id BIGSERIAL PRIMARY KEY,
speciesId INTEGER REFERENCES species(id),
es_AR VARCHAR(255),
en_US VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL UNIQUE,
status INTEGER
);
CREATE TABLE IF NOT EXISTS provinces(
id INTEGER PRIMARY KEY,
name VARCHAR(256) UNIQUE,
latitude FLOAT(8),
longitude FLOAT(8)
);
CREATE TABLE IF NOT EXISTS departments(
id INTEGER PRIMARY KEY,
name VARCHAR(256),
latitude FLOAT(8),
longitude FLOAT(8),
province VARCHAR(256) REFERENCES provinces(name)
);
CREATE TABLE IF NOT EXISTS pets (
id BIGSERIAL PRIMARY KEY,
petName VARCHAR(255),
species INTEGER REFERENCES species(id),
breed INTEGER REFERENCES breeds(id),
department INTEGER REFERENCES departments(id),
province INTEGER REFERENCES province(id),
vaccinated BOOLEAN NOT NULL,
gender VARCHAR(255) NOT NULL,
description TEXT,
birthDate DATE,
uploadDate DATE NOT NULL DEFAULT CURRENT_DATE,
price INTEGER,
ownerId INTEGER REFERENCES users(id),
status INTEGER
);
CREATE TABLE IF NOT EXISTS images (
id BIGSERIAL PRIMARY KEY,
img BYTEA,
petId INTEGER REFERENCES pets(id)
);
CREATE TABLE IF NOT EXISTS requests (
id BIGSERIAL primary key,
ownerId INTEGER references users(id),
petId INTEGER references pets(id),
status INTEGER,
creationDate DATE DEFAULT CURRENT_DATE,
CONSTRAINT norepeats UNIQUE(ownerId,petId)
);