CREATE TABLE IF NOT EXISTS species (
id INTEGER PRIMARY KEY,
es_AR VARCHAR(255),
en_US VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS breeds (
id INTEGER PRIMARY KEY,
speciesId INTEGER REFERENCES species(id),
es_AR VARCHAR(255),
en_US VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL UNIQUE,
status INTEGER NOT NULL,
locale CHAR(7)
);
CREATE TABLE IF NOT EXISTS admins (
id INTEGER REFERENCES users(id) PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS reviews (
id INTEGER PRIMARY KEY,
ownerId INTEGER NOT NULL REFERENCES users(id),
targetId INTEGER NOT NULL REFERENCES users(id),
score INTEGER  NOT NULL CHECK (score > 0 AND score < 6),
description TEXT,
creationDate DATE DEFAULT CURRENT_DATE,
status INTEGER NOT NULL,
CONSTRAINT owner_target_diff CHECK (ownerId <> targetId),
CONSTRAINT owner_target_unique UNIQUE (ownerId, targetId)
);
CREATE TABLE IF NOT EXISTS provinces(
id INTEGER PRIMARY KEY,
name VARCHAR(256) NOT NULL UNIQUE,
latitude FLOAT(8),
longitude FLOAT(8)
);
CREATE TABLE IF NOT EXISTS departments(
id INTEGER PRIMARY KEY,
name VARCHAR(256) NOT NULL,
latitude FLOAT(8),
longitude FLOAT(8),
province VARCHAR(256) REFERENCES provinces(name)
);
CREATE TABLE IF NOT EXISTS pets (
id INTEGER PRIMARY KEY,
petName VARCHAR(255),
species INTEGER REFERENCES species(id),
breed INTEGER REFERENCES breeds(id),
department INTEGER REFERENCES departments(id),
province INTEGER REFERENCES provinces(id),
vaccinated BOOLEAN NOT NULL,
gender VARCHAR(255) NOT NULL,
description TEXT,
birthDate DATE,
uploadDate DATE DEFAULT CURRENT_DATE,
price INTEGER,
ownerId INTEGER NOT NULL REFERENCES users(id),
status INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS images (
id INTEGER PRIMARY KEY,
img BINARY,
petId INTEGER REFERENCES pets(id)
);
CREATE TABLE IF NOT EXISTS requests (
id INTEGER primary key,
ownerId INTEGER references users(id),
petId INTEGER references pets(id),
status INTEGER,
creationDate DATE DEFAULT CURRENT_DATE,
CONSTRAINT norepeats UNIQUE(ownerId, petId)
);
CREATE TABLE IF NOT EXISTS tokens (
id INTEGER PRIMARY KEY,
token VARCHAR(36),
userId INTEGER REFERENCES users(id),
expirationDate DATE
);
