$(document).ready(function() {
    if(userScore === 0){
        document.getElementById("star1").classList += " far fa-star"
        document.getElementById("star2").classList+= " far fa-star"
        document.getElementById("star3").classList+= " far fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 0 && userScore <= 0.5){
        document.getElementById("star1").classList+= " fas fa-star-half-alt"
        document.getElementById("star2").classList+= " far fa-star"
        document.getElementById("star3").classList+= " far fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 0.5 && userScore <= 1){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " far fa-star"
        document.getElementById("star3").classList+= " far fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 1 && userScore <= 1.5){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star-half-alt"
        document.getElementById("star3").classList+= " far fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 1.5 && userScore <= 2){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " far fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 2 && userScore <= 2.5){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " far fa-star-half-alt"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 2.5 && userScore <= 3){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " fas fa-star"
        document.getElementById("star4").classList+= " far fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 3 && userScore <= 3.5){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " fas fa-star"
        document.getElementById("star4").classList+= " fas fa-star-half-alt"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 3.5 && userScore <= 4){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " fas fa-star"
        document.getElementById("star4").classList+= " fas fa-star"
        document.getElementById("star5").classList+= " far fa-star"
    }else if(userScore > 4 && userScore <= 4.5){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " fas fa-star"
        document.getElementById("star4").classList+= " fas fa-star"
        document.getElementById("star5").classList+= " fas fa-star-half-alt"
    }else if(userScore > 4.5 && userScore <= 5){
        document.getElementById("star1").classList+= " fas fa-star"
        document.getElementById("star2").classList+= " fas fa-star"
        document.getElementById("star3").classList+= " fas fa-star"
        document.getElementById("star4").classList+= " fas fa-star"
        document.getElementById("star5").classList+= " fas fa-star"
    }
});